add infra-terraform-modules
dBildungsplattform/infra-terraform-modules pull request #2
Opened 2023-09-01 06:55 UTC by sahassou

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-09-03 20:10 UTC, sahassou commented
This code defines a GitHub Actions workflow that performs static code analysis on Terraform code using Checkov and TFLint.

2023-09-04 09:15 UTC, aimee-889 commented on .github/workflows/generate-tf-doc.yml
> +  push:
Best is to only execute this when a PR is open and code has changes in the modules folder
pull_request:
    branches: 
      - main
    paths: 
      - 'modules/**'

2023-09-04 09:16 UTC, aimee-889 commented on .github/workflows/generate-tf-doc.yml
> +  workflow_call:
workflow call is only needed if we want to call this workflow from somewhere else, which is currently not the case. So the push on pr on main can be the only event that triggers the workflow

2023-09-04 09:25 UTC, aimee-889 commented on .github/workflows/generate-tf-doc.yml
> +    - name: Render Terraform-Docs
find-dir parameter also should get added so that root/README.md is not overwritten  and inputs values have to get updated. Can be found here https://github.com/hpi-schul-cloud/infra-schulcloud/blob/master/.github/workflows/github-action-create-tf-docs-and-helm-docs.yaml

2023-09-04 09:32 UTC, aimee-889 commented on .github/workflows/static-code-analysis.yml
> +      - uses: actions/checkout@v2
if possible actions/checkout@v3 should get used - see Actions Warning "The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/"

2023-09-04 09:52 UTC, aimee-889 commented on .github/workflows/static-code-analysis.yml
> +      - name: Set up Python 3.11
per default python 10 is already installed on the runner - see: https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md - i think this setup step is not necessarily needed?

2023-09-04 11:05 UTC, aimee-889 commented on .github/workflows/static-code-analysis.yml
> +        uses: bridgecrewio/checkov-action@master
master should not get used but a tag. Furthermore we would like to get some output. @dimapin CLI or/and Sarif?
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2

2023-09-04 12:21 UTC, aimee-889 commented on modules/conventions-coordinates/variables.tf
> +    "project" = "<project>"
i would delete the default values here as well

2023-09-04 12:22 UTC, aimee-889 commented on modules/conventions-instances/locals.tf
> +locals {
this module should get deleted

2023-09-04 12:23 UTC, aimee-889 commented on modules/ionos-loadbalancer-ip/variables.tf
> +  description = "Top-level domain mapping for environments"
would delete this default values

2023-09-04 12:24 UTC, aimee-889 commented on modules/telekom-dns/locals.tf
> +
dns_a_entry = var.dns_a_entry == "" ? module.conventions_coordinates.cluster_dns : var.dns_a_entry

2023-09-04 13:22 UTC, sahassou commented on .github/workflows/static-code-analysis.yml
> +      - name: Set up Python 3.11
I ran the code with Python 3.10 and received the error message below. Therefore, I decided to install Python 3.11 after checking this homepage

 [https://[raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)](url) 


 "**Run actions/setup-python@v4
Installed versions
  Version 3.1 was not found in the local cache
  Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json**"

2023-09-05 04:47 UTC, aimee-889 commented on .github/workflows/generate-tf-doc.yml
> +      - '.github/templates/**'
the modules folder should get added

2023-09-11 06:57 UTC, dimapin requested changes
Here are some files from a provider committed which should not be in the code. Please remove them

2023-09-11 06:57 UTC, dimapin commented on .github/workflows/static-code-analysis.yml
> +        uses: bridgecrewio/checkov-action@master
Both

2023-09-11 16:15 UTC, aimee-889 commented on README.md
> +# Usage
please update this README, it got overwritten by the GHA but it hould briefly state that we keep our terraform modules in this repo.

2023-09-11 16:17 UTC, aimee-889 commented
https://github.com/dBildungsplattform/infra-terraform-modules/tree/aimee-gha-test/.github/workflows GHA actions for the time being should be used as they are configured in here. Further adjustments can be done in the future.

2023-09-12 11:01 UTC, aimee-889 approved these changes

2023-09-14 06:40 UTC, dimapin approved these changes

2023-09-14 07:47 UTC, merged