dbp 929 linux server for email
dBildungsplattform/infra-terraform-modules pull request #33
Opened 2024-07-30 13:29 UTC by jdabat

# Description
added module for creating a lan and firewall rules

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-07-31 18:46 UTC, dimapin commented on modules/ionos-lan-and-firewall/main.tf
> +   name          = format( "%s-%s",var.name,"intern-connection-lan")
The suffix intern-connection-lan contradicts the setting public-true. Why don't you use the name which is given with the variable

2024-07-31 18:46 UTC, dimapin commented on modules/ionos-lan-and-firewall/main.tf
> +  dhcp            = true
This should be optional

2024-08-01 11:07 UTC, jdabat commented on modules/ionos-lan-and-firewall/main.tf
> +  dhcp            = true
This module is not fully implemented, still missing parts. Currently the needed parts are implemented. extending the module is still a TODO

2024-08-01 15:36 UTC, dimapin requested changes

2024-08-01 15:36 UTC, dimapin commented on modules/ionos-lan-and-firewall/main.tf
> +   name          = format( "%s-%s-%x",var.name,var.is_public? "public":"private","-connection-lan")
The format should be %s-%s-%s

2024-08-02 08:37 UTC, dimapin approved these changes

2024-08-02 08:38 UTC, merged